## Why you shouldn't interpret all your regression coefficients as causal estimands.

library(tidyverse)
library(dagitty)
library(ggdag)


# suppose our data is generated by the following causal structure
dagify(Y ~ X + Z + W,
       X ~ Z,
       Z ~ W) |>
  ggdag() +
  theme_dag()

# simulate some data -------------------------

N <- 10000

W <- rnorm(N) # W is exogenous

Z <- 3*W + rnorm(N) # Z is caused by W

X <- -3*Z + rnorm(N) # X is caused by Z

Y <- 2*X + 3*Z + 4*W + rnorm(N) # Y is caused by X, Z, and W



## Estimation ------------------

# What must you control for in order to estimate the effect of X on Y?
# What must you control for in order to estimate the effect of Z on Y?



